;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	cua--prefix-override-handler
	cua-copy-region
	cua-paste
	))

(setq mc/cmds-to-run-once
      '(
	describe-key
	mark-whole-buffer
	mc/mark-next-lines
	mouse-buffer-menu
	mouse-save-then-kill
	mouse-set-region
	move-text-down
	w32-drag-n-drop
	))
